services:
  - type: web
    name: webtech-bung-backend
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true
